language: node_js
node_js: [node]
cache: npm
script: npm run validate
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    tags: true
  token:
    secure: bCIP8P9O18GAewchrZejZVTxAFfObdSAZhzEQLTbCY5qG2EX3zzM0sFDMbT3OKRzXT9tjOLjfknBq8DP0qdE+zCy4aGT8kzcdHHpeqgyn6fZxGr/2OT8NvU/WI+nq5z8HQ3YnpKQDs8sQoO6IBFWdlzurkbm3/4ae6MRraiMvd+x4Z9HuiY63JAxkNX3+E+OcvIfsLNdbqHx1LGfG07sRqdKbgLOhr24QJyomUylH2PGZhaRVtvT17XPSQ5YiWjxsRNYq4wzyxtM/ltsCbdppINjAb1SveUOTMNTOkW+0dumWHPx6B2KkVfDb8AwNO0SKdj23pcjhtDpOaAJU2Ej+khR3Ulwe03QwKfyATpRlFm3L4Y9E/f/GINAHyxTWo6xhEye2fB8ZzLCLF5CxVc9PYzm6ldDNFn/Zrylp6jcHNSotOo+7nIfO0Nvye/aDL4cucW7pPR1yW4rsNTCbOkNKqAbzAnvNE4ROWfY57J7keru5hGFhOsyYG01mHIiwn6bXh/F8BOmKlEgJ/Ta3Nz4UIDt7s8QRzP7TABvSu9pny7scCH2nNRIPK2NewgaxVwTrpniwEQSU+6MFAhMfQQVCNU/BZGjGgAaFV/gwCO1rhs1NRfzfYUawhrVMbtMmXpgKxhaKqNtHZzOtMaaBt13s5ZPEfUe8FOk0vUGK5gp7d8=
